on: 
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Environment
        run: |
          pwd
          ls -l
          git branch
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
      - name: Deploy to QA
        run: |
          export VKD_ENVIRONMENT=qa
          npm run deploy