on: 
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Environment
        run: |
          pwd
          ls -l
          git branch
      - name: Install
        run: npm run ci:all
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test