on: 
  push:
    branches:
      - "master"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  main-prep:
    runs-on: ubuntu-latest
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Environment
        run: |
          pwd
          ls -l
          git branch
      - name: Install
        run: npm ci
      - name: Preserve artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: |
            ./*
          retention-days: 5
  main-test:
    needs: [main-prep]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test
      - name: Preserve artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: |
            ./*
          retention-days: 5
  main-deploy-qa:
    needs: [main-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QA
        run: |
          export VKD_ENVIRONMENT=qa
          npm run deploy:ci