on: 
  push:
    branches:
      - "master"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  main-prep:
    runs-on: ubuntu-latest
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Environment
        run: |
          pwd
          ls -l
          git branch
      - name: Install
        run: npm ci
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
  main-test:
    needs: [main-prep]
    runs-on: ubuntu-latest
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        run: npm test -- --forceExit --detectOpenHandles
  main-deploy-qa:
    needs: [main-test]
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Deploy to QA
        run: |
          export VKD_ENVIRONMENT=qa
          npm run deploy:ci
      - name: Test QA
        run: . ./.github/scripts/test-qa.sh
  main-diff-prod:
    needs: [main-deploy-qa]
    runs-on: ubuntu-latest
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Diff production infrastructure
        run: |
          export VKD_ENVIRONMENT=prod
          npm run diff
