on: 
  push:
    branches:
      - "master"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  main-prep:
    runs-on: ubuntu-latest
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Environment
        run: |
          pwd
          ls -l
          git branch
      - name: Install
        run: npm ci
  main-test:
    needs: [main-prep]
    runs-on: ubuntu-latest
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Test
        run: npm run test
  main-deploy-qa:
    needs: [main-test]
    runs-on: ubuntu-latest
    steps:
      - name: Use setup node action
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Deploy to QA
        run: |
          export VKD_ENVIRONMENT=qa
          npm run deploy:ci
      - name: Test QA
        run: |
          . ./.github/scripts/test-qa.sh
